<!DOCTYPE html>
<html lang="{{ $theme_config['default_language'] ?? 'en-US' }}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="icon" href="/theme/{{ $theme }}/images/logo.png">
  
  <!-- Dynamic title from Laravel settings -->
  <title>{{ $title }}</title>
  
  <!-- Preload fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  
  <!-- Global styles -->
  <style>
    @media (min-width: 769px) {html, body, div, main, section, article, aside, nav {scrollbar-width: none !important;-ms-overflow-style: none !important;}::-webkit-scrollbar, ::-webkit-scrollbar-button, ::-webkit-scrollbar-track, ::-webkit-scrollbar-track-piece, ::-webkit-scrollbar-thumb, ::-webkit-scrollbar-corner, ::-webkit-resizer {display: none !important;width: 0 !important;height: 0 !important;background: transparent !important;}}html, body {width: 100%;height: 100%;}@media (min-width: 769px) {* {scrollbar-width: none !important;-ms-overflow-style: none !important;}} html, body {margin: 0;padding: 0;width: 100%;height: 100%;overflow-x: hidden;}#app {width: 100%;height: 100%;}html.preloader-active, body.preloader-active {overflow: hidden !important;}
    
    /* Custom CSS from theme configuration */
    {!! $theme_config['custom_css'] ?? '' !!}
  </style>
  
  <!-- Version badge styles -->
  <style>
    .app-version {position: fixed;left: 6px;bottom: 4px;font-size: 9px;color: rgba(0, 0, 0, 0.35);user-select: none;pointer-events: none;z-index: 5;}
  </style>
  
  <!-- Load dynamic configuration first -->
  <script>
    // ProxyBD configuration loader with fallback system
    window.PB_LOADER = {
      configFileName: 'config.js',
      configTimeout: 3000,
      maxRetries: 2
    };
  </script>
  
  <!-- Load dynamic config.js generated by Laravel -->
  <script src="/theme/{{ $theme }}/config.js?v={{ time() }}" defer></script>

  <!-- Load ProxyBD theme assets -->
  <script type="module" crossorigin src="/theme/{{ $theme }}/assets/index-sC8Xq0xY.js"></script>
</head>
<body>
  <div id="app"></div>
  
  <!-- Version badge -->
  <div class="app-version">{{ $version }}</div>

  <!-- Custom HTML from theme configuration -->
  {!! $theme_config['custom_html'] ?? '' !!}
</body>
</html>